# Generated by Django 6.0.4 on 2026-05-14 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imovel_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='imoveis.imovel')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_como_locador', to=settings.AUTH_USER_MODEL)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_como_locatario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('locatario', 'imovel')},
            },
        ),
    ]
