# Generated by Django 4.2.11 on 2026-07-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imovel_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='banheiros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(default=0),
        ),
    ]
