# Generated by Django 6.0.4 on 2026-05-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='locador',
        ),
    ]
