# Generated by Django 4.2.11 on 2026-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_imovel_garagem_imovel_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Área Útil'),
        ),
    ]
