services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_printii
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DB_NAME=db_printii
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  mysql_data:
