# Generated by Django 6.0.4 on 2026-04-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('cpf', models.TextField(max_length=11)),
                ('idade', models.TextField()),
                ('sexo', models.TextField()),
                ('profissao', models.TextField()),
                ('rua', models.TextField()),
                ('bairro', models.TextField()),
                ('cidade', models.TextField(default='Cedro')),
                ('estado', models.TextField(default='CE')),
                ('numero', models.IntegerField()),
                ('email', models.TextField()),
                ('senha', models.TextField()),
                ('tipo_de_usuario', models.CharField(choices=[('locador', 'Locador'), ('locatario', 'Locatário')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
