# Generated by Django 4.2.11 on 2026-06-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuarios",
            "0006_alter_user_bairro_alter_user_cidade_alter_user_cpf_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
